Release 1 9 0
btcpayserver/blog pull request #31
Opened 2023-04-12 14:34 UTC by Bangalisch

Yoo 

Draft blog post for 1.9.0 release, please leave reviews!

2023-04-12 16:33 UTC, petzsch requested changes
just minor stuff. Great article. 👍

2023-04-12 16:33 UTC, petzsch commented on blog/_posts/btcpay-server-1-9-0.md
> +We're excited to announce the version of BTCPay Server v1.9.0, bringing you many new features, improvements, and bug fixes. This major release is a big step forward, and we can't wait for you to try
```suggestion
We're excited to announce version v1.9.0 of BTCPay Server, bringing you many new features, improvements, and bug fixes. This major release is a big step forward, and we can't wait for you to try it out!
```

2023-04-12 16:33 UTC, petzsch commented on blog/_posts/btcpay-server-1-9-0.md
> +With the custodian wallet plugin, you can directly, out of your BTCPay Server, send the amounts of bitcoin necessary to the exchange and convert into fiat for suppliers.
```suggestion
With the custodian wallet plugin, you can directly, out of your BTCPay Server, send the amounts of bitcoin necessary to the exchange and convert them into fiat (i.e. for paying your suppliers). 
```

2023-04-12 16:33 UTC, petzsch commented on blog/_posts/btcpay-server-1-9-0.md
> +Now, in the left menu bar of BTCPay Server, you'll find "add custodian" below your Bitcoin and Lightning wallet. However, before we can add the custodian, you must install the Kraken plugin. Find "Ma
```suggestion
Now, in the left menu bar of BTCPay Server, you'll find "add custodian" below your Bitcoin and Lightning wallet. However, before we can add the custodian, you must install the Kraken plugin. Find "Manage plugins” in the left menu bar and install the Kraken plugin, your BTCPay Server will ask for a restart. 
```

2023-04-12 16:33 UTC, petzsch commented on blog/_posts/btcpay-server-1-9-0.md
> +## 🚨 Be warned of scammers!
```suggestion
## 🚨 Beware of scammers!
```

just personal preference. I guess the old headline would also work.

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +## 🛍️Point of Sale, NFC and receipts
```suggestion
## 🛍️ Point of Sale, NFC and receipts
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +## 📒New recovery seed phrase view!
```suggestion
## 📒 New recovery seed phrase view! 
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +## 📚Wallet Labels export - BIP-329
```suggestion
## 📚 Wallet Labels export - BIP-329 
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +## 🤝Restructuring how metadata is viewed.
```suggestion
## 🤝 Restructuring how metadata is viewed
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +Now, in the left menu bar of BTCPay Server, you'll find "add custodian" below your Bitcoin and Lightning wallet. However, before we can add the custodian, you must install the Kraken plugin. Find "Ma
```suggestion
Now, in the left menu bar of BTCPay Server, you'll find "Add custodian" below your Bitcoin and Lightning wallet. However, before we can add the custodian, you must install the Kraken plugin. Find "Manage plugins” in the left menubar and install the Kraken plugin, your BTCPay Server will restart. 
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +To get custodian wallets into your BTCPay Server, we must first enable experimental features in Server settings. Underneath the Policies tab, scroll down to Maintenance Settings, tick the box in fron
```suggestion
To get custodian wallets into your BTCPay Server, we must first enable experimental features in Server Settings. Underneath the Policies tab, scroll down to Maintenance Settings, tick the box in front of "enable experimental features'' and save the server settings at the bottom. 
```

2023-04-12 16:35 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +After installing the Kraken plugin, click "add custodian"; the only option available so far is Kraken. Select and click continue. Stay calm about the warnings; the plugin tries to connect immediately
```suggestion
After installing the Kraken plugin, click "add custodian"; the only option available so far is Kraken. Select that and click continue. Stay calm about the warnings; the plugin tries to connect immediately. Fill out the fields as instructed, and you should be set up with the Kraken custodian wallet plugin! For non-technical shopkeepers, all features can be automated using Zapier. Using the new custodian account framework, plugin developers are now able to code their own plugins and add support for exchanges and other custodians, like brokers or online payment systems to BTCPay Server. 
```

2023-04-12 20:11 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +Merchants utilizing NFC functionality will be happy that we’ve added additional improvements. Earlier, if a customer wanted to pay via NFC, a merchantT had to tap the "Pay By NFC" button. From now on
```suggestion
Merchants utilizing NFC functionality will be happy that we’ve added additional improvements. Earlier, if a customer wanted to pay via NFC, the merchant had to tap the "Pay by NFC" button. From now on, if the browser already has permission, you no longer have to click the button. Just tap the NFC card to initiate the payment!
```

2023-04-12 20:11 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +The next-gen checkout - V2 received additional improvements and is now a default for all new stores!
```suggestion
Our next-gen checkout received additional improvements and is now the default for all new stores! 
```

2023-04-12 20:11 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +On the customer-facing side, when the client has paid your store or invoice, the Checkout will show the on-chain transaction status, and if it still needs to confirm, when it confirms, it's party tim
```suggestion
On the customer-facing side, when the client has paid your store or invoice, the checkout will show the on-chain transaction status, and if it still needs to confirm. Once it confirms, it's party time – we even brought some confetti! 
```

2023-04-12 20:11 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +After adding the labels locally on your transactions, we've now gone ahead and implemented [BIP-329](https://github.com/btcpayserver/btcpayserver/pull/4799), where wallet labels are exportable. If yo
```suggestion
After adding the labels locally on your transactions, we've now gone ahead and implemented [BIP-329](https://github.com/btcpayserver/btcpayserver/pull/4799), which standardizes the export of wallet labels. If you've added labels to your transactions and moved to another wallet (that supports BIP-329), you can take your labels with you! No longer a mess in recognizing what your transactions were! 
```

2023-04-12 20:11 UTC, dennisreimann commented on blog/_posts/btcpay-server-1-9-0.md
> +You can now customize the [invoice metadata](https://docs.btcpayserver.org/Development/InvoiceMetadata/) for payments received through a Lightning Address. Additionally, Payment Proof will now appear
```suggestion
You can now customize the [invoice metadata](https://docs.btcpayserver.org/Development/InvoiceMetadata/) for payments received through a Lightning Address. Additionally, payment proofs will now appear in the receipt data.
```

2023-04-13 12:17 UTC, pavlenex approved these changes

2023-04-13 12:18 UTC, merged